name: RedisChat
version: '${project.version}'
main: dev.unnm3d.redischat.RedisChat
author: Unnm3d
api-version: 1.16
libraries:
  - io.lettuce:lettuce-core:6.2.4.RELEASE
  - org.yaml:snakeyaml:1.27
  - org.snakeyaml:snakeyaml-engine:2.3
  - org.jetbrains:annotations:19.0.0
  - com.zaxxer:HikariCP:5.0.1
depend:
  - PlaceholderAPI
softdepend:
  - Oraxen
loadbefore:
  - CMI
  - CMILib
  - Essentials
  - EssentialsChat
commands:
  redischat:
    description: RedisChat command
    usage: /redischat <reload>
    permission: redischat.admin
  ignore:
    description: Ignore command
    permission: redischat.ignore
  msg:
    description: Sends a private message to a player
    aliases:
      - message
    usage: /msg <player> <message>
    permission: redischat.message
  reply:
    description: Replies to the last player who sent you a message
    aliases: [r]
    permission: redischat.message
  broadcast:
    description: Broadcasts a message to the server
    aliases: [bc]
    usage: /broadcast <message>
    permission: redischat.broadcast
  clearchat:
    description: Clears the chat
    aliases: [cc]
    usage: /clearchat
    permission: redischat.clearchat
  invshare:
    description: 'Invshare'
  staffchat:
    description: Staffchat command
    aliases: [sc]
    permission: redischat.staffchat
permissions:
  redischat.useformatting:
    description: Allows to send formatted messages
    default: op
  redischat.broadcast:
    description: Allows to use the /broadcast command
    default: op
  redischat.clearchat:
    description: Allows to use the /clearchat command
    default: op
  redischat.message:
    description: Allows to use the /msg command
    default: op
  redischat.ignore:
    description: Allows to use the /ignore command
    default: op
  redischat.staffchat:
    description: Allows to use the /staffchat command
    default: op
  redischat.bypass_rate_limit:
    description: Bypass the rate limit
    default: false
  redischat.admin:
    description: Allows to use the /redischat command
    default: op
    children:
      - redischat.useformatting
      - redischat.broadcast
      - redischat.clearchat
      - redischat.message
      - redischat.ignore
      - redischat.spycommand
      - redischat.bypass_rate_limit
      - redischat.editmessage
      - redischat.staffchat
  redischat.default:
    description: Allows you to use default commands
    default: true
    children:
      - redischat.message
      - redischat.ignore


